version: 2
jobs:
  postgres: &postgres
    working_directory: &workdir ~/solidus
    environment: &environment
      DB: postgresql
      DB_HOST: localhost
      DEFAULT_MAX_WAIT_TIME: 10
      SOLIDUS_RAISE_DEPRECATIONS: true
      CIRCLE_TEST_REPORTS: /tmp/test-results
      CIRCLE_ARTIFACTS: /tmp/test-artifacts
    docker:
      - image: &image circleci/ruby:2.5-node-browsers
      - image: jhawthorn/circleci-postgres-fast
        environment:
          POSTGRES_USER: root
    parallelism: &parallelism 3
    steps: &steps
      - checkout

      - restore_cache:
          keys:
            - solidus-gems-v1-{{ .Branch }}
            - solidus-gems-v1

      - run: |
          bundle install --path=vendor/bundle

      - cache-save:
          key: solidus-gems-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run Tests
          command: ./build-ci.rb test

      - store_artifacts:
          path: /tmp/test-artifacts
          destination: test-artifacts

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

  mysql: &mysql
    working_directory: *workdir
    environment: &mysql_environment
      <<: *environment
      DB: mysql
      DB_HOST: 127.0.0.1
    docker:
      - image: *image
      - image: circleci/mysql:5.7-ram
    parallelism: *parallelism
    steps: *steps

  postgres_rails51:
    <<: *postgres
    environment:
      <<: *environment
      RAILS_VERSION: '~> 5.1.0'

  mysql_rails51:
    <<: *mysql
    environment:
      <<: *mysql_environment
      RAILS_VERSION: '~> 5.1.0'

workflows:
  version: 2
  build:
    jobs:
      - postgres
      - mysql
      - postgres_rails51
      - mysql_rails51
